# Module manifest for module 'SQL Agent Job Deploy'
#
# Generated by: Richie Lee
#
# Generated on: 15/05/2017
#
 
@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'salt.psm1'
 
    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules = @()
 
    # Version number of this module.
    ModuleVersion = '1.0.2.1'
 
    # ID used to uniquely identify this module
    GUID = '068b8176-32d3-486d-9dbf-77c45c7f8d4a'
 
    # Author of this module
    Author = 'Richie Lee'
 
    # Company or vendor of this module
    CompanyName = 'Sabin.IO'
 
    # Copyright statement for this module
    Copyright = 'Sabin.IO 2017'
 
    # Description of the functionality provided by this module
    Description = 'Module to deploy SQL Agent Jobs to SQL Server Instance.
               Supports creation of jobs, schedules and job steps of type SQL, PowerShell
               and dtsx packages. Requires the SQl Agent Job to be in a set format in XML.
		Requires SMO to be installed on box.'
 
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = ''
 
    # Name of the Windows PowerShell host required by this module
    PowerShellHostName = ''
 
    # Minimum version of the Windows PowerShell host required by this module
    PowerShellHostVersion = ''
 
    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = ''
 
    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = ''
 
    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture = ''
 
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()
 
    # Script files (.psm1) that are run in the caller's environment prior to importing this module
    ScriptsToProcess = @()
 
    # Format files (.psm1xml) to be loaded when importing this module
    FormatsToProcess = @()
 
    # Functions to export from this module
    FunctionsToExport = @(
       'Get-Job',   
       'Get-SqlAgentAsXml',
       'Get-Xml',
       'Connect-SqlConnection',
       'Disable-Job',
       'Disable-JobNotifications',
       'Disable-JobSchedules',
       'Disconnect-SqlConnection',
       'Enable-Job',
       'Enable-JobSchedules',
       'Install-SaltNuGet',
       'Install-SaltSmo',
       'Set-Job',
       'Set-JobCategory',
       'Set-JobNotification',
       'Set-JobOperator',
       'Set-JobOwner',
       'Set-JobProperties',
       'Set-JobSchedules',
       'Set-JobSteps',
       'Test-JobIsIdle',
       'Test-CurrentPermissions',
       'Test-SQLServerAgentService'
    )
 
    # Cmdlets to export from this module
    CmdletsToExport = '*'
 
    # Variables to export from this module
    VariablesToExport = '*'
 
    # Aliases to export from this module
    AliasesToExport = '*'
 
    # List of all modules packaged with this module
    ModuleList = @()
 
    # List of all files packaged with this module
    FileList = @()
 
    # Private data to pass to the module specified in ModuleToProcess
    PrivateData = ''
 
}